# Generated by Django 4.2.27 on 2026-02-23 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_businessrole'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CV', 'CV'), ('CERTIFICATE', 'Certificate'), ('CONTRACT', 'Signed Contract'), ('NDA', 'NDA'), ('PERFORMANCE', 'Performance Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='budget_allocation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='department',
            name='cost_center_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('ADMINISTRATIVE', 'Administrative'), ('EXECUTIVE', 'Executive')], default='OPERATIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='employees.department'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='employees_d_is_acti_97e269_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_type'], name='employees_d_departm_93d963_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employment_type'], name='employees_e_employm_09537f_idx'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedepartmentrole',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_roles', to='employees.department'),
        ),
        migrations.AddField(
            model_name='employeedepartmentrole',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedepartmentrole',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedepartmentrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='accounts.businessrole'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['document_type'], name='employees_e_documen_3808ed_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedepartmentrole',
            index=models.Index(fields=['is_active'], name='employees_e_is_acti_b483c1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedepartmentrole',
            index=models.Index(fields=['department'], name='employees_e_departm_de0552_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedepartmentrole',
            index=models.Index(fields=['role'], name='employees_e_role_id_3738be_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeedepartmentrole',
            constraint=models.UniqueConstraint(fields=('employee', 'department', 'role'), name='unique_employee_department_role'),
        ),
    ]
