# Generated by Django 4.2.27 on 2026-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeedocument_user_ownership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeedocument',
            new_name='employees_e_user_id_1e9249_idx',
            old_name='employees_e_user_id_9d2de1_idx',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Permanent'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant')], default='FULL_TIME', max_length=20),
        ),
    ]
