# Generated by Django 4.2.27 on 2026-02-23 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Jambas HRMS', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Human Resource Portal', max_length=180)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')])),
                ('secondary_color', models.CharField(default='#64748b', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')])),
                ('accent_color', models.CharField(default='#3b82f6', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')])),
                ('sidebar_color', models.CharField(default='#0f172a', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')])),
                ('body_bg_color', models.CharField(default='#f1f5f9', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branding Settings',
                'verbose_name_plural': 'Branding Settings',
            },
        ),
    ]
