# Generated by Django 4.2.27 on 2026-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='public_access_code_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='public_access_code_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
