# Generated by Django 4.2.27 on 2026-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brandingsettings_public_access_code_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='public_access_code_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
