# Generated by Django 4.2.27 on 2026-02-24 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brandingsettings_public_access_code_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_bg_color',
            field=models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_left_text',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_link_text',
            field=models.CharField(blank=True, default='DEVTOWN TECHNOLOGIES', max_length=120),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_link_url',
            field=models.URLField(blank=True, default='https://www.devtownhosting.com'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_right_text',
            field=models.CharField(blank=True, default='System developed by', max_length=220),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_text_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='primary_hover_color',
            field=models.CharField(default='#1d4ed8', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')]),
        ),
    ]
