# Generated by Django 4.2.27 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brandingsettings_footer_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='hr_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='hr_title',
            field=models.CharField(blank=True, default='Human Resource', max_length=120),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='hr_signature',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
