# Generated by Django 4.2.27 on 2026-02-24

from django.db import migrations


def seed_company_info(apps, schema_editor):
    BrandingSettings = apps.get_model('core', 'BrandingSettings')

    try:
        obj = BrandingSettings.objects.get(pk=1)
    except BrandingSettings.DoesNotExist:
        obj = BrandingSettings(pk=1)

    updated_fields = []

    tagline = (
        'Integrated solutions in printing, branding, IT products, IT support services, '
        'safety gears, medical supplies, and stationery.'
    )
    if not (obj.tagline or '').strip():
        obj.tagline = tagline
        updated_fields.append('tagline')

    if not (obj.company_phone or '').strip():
        obj.company_phone = '+256 200 902 849'
        updated_fields.append('company_phone')

    if not (obj.company_email or '').strip():
        obj.company_email = 'info@jambasimaging.com'
        updated_fields.append('company_email')

    if not (obj.company_address or '').strip():
        obj.company_address = 'F-26, Nasser Road Mall, Kampala – Uganda'
        updated_fields.append('company_address')

    if updated_fields:
        # Use a plain save() so this works both when the row already exists
        # and when we're inserting a new singleton row in a fresh/test DB.
        obj.save()


def unseed_company_info(apps, schema_editor):
    # No-op: we don't want to delete user-entered branding info on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brandingsettings_company_details_and_hr_signature'),
    ]

    operations = [
        migrations.RunPython(seed_company_info, reverse_code=unseed_company_info),
    ]
