# Generated by Django 4.2.27 on 2026-02-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='login_show_branding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='login_show_logo',
            field=models.BooleanField(default=False),
        ),
    ]
