# Generated by Django 4.2.27 on 2026-02-27 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_brandingsettings_login_show_branding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='text_light_color',
            field=models.CharField(default='#f8fafc', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='text_main_color',
            field=models.CharField(default='#1e293b', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='text_muted_color',
            field=models.CharField(default='#64748b', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')]),
        ),
    ]
