# Generated by Django 4.2.27 on 2026-02-27 15:05

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brandingsettings_text_light_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(default='INBOX', max_length=255)),
                ('uid', models.PositiveBigIntegerField()),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('references', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('to', models.TextField(blank=True)),
                ('cc', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inbound Email',
                'verbose_name_plural': 'Inbound Emails',
            },
        ),
        migrations.CreateModel(
            name='InboxState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(default='INBOX', max_length=255, unique=True)),
                ('uidvalidity', models.PositiveBigIntegerField(default=0)),
                ('last_uid', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inbox State',
                'verbose_name_plural': 'Inbox States',
            },
        ),
        migrations.CreateModel(
            name='InboundEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('file', models.FileField(upload_to=core.models.inbox_attachment_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.inboundemail')),
            ],
            options={
                'verbose_name': 'Inbound Email Attachment',
                'verbose_name_plural': 'Inbound Email Attachments',
            },
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['mailbox', '-uid'], name='inbound_mailbox_uid_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(fields=('mailbox', 'uid'), name='unique_inbound_email_mailbox_uid'),
        ),
    ]
