# Generated by Django 4.2.27 on 2026-02-28 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_brandingsettings_sidebar_hover_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='sidebar_active_link_color',
            field=models.CharField(default='#3b82f6', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid HEX color (e.g. #2563eb).', regex='^#(?:[0-9A-Fa-f]{3}){1,2}$')]),
        ),
    ]
