# Generated by Django 4.2.27 on 2026-02-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('approval_authority_level', models.PositiveSmallIntegerField(default=0)),
                ('financial_authorization_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('department_scope', models.ForeignKey(blank=True, help_text='Optional. If set, role is scoped to this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='accounts_bu_code_0e5d53_idx'), models.Index(fields=['is_active'], name='accounts_bu_is_acti_8d301c_idx')],
            },
        ),
    ]
