# Generated by Django 4.2.27 on 2026-02-24 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_by_department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by_position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='noticeboard.notice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['notice'], name='noticeboard_notice__27e0e0_idx'), models.Index(fields=['created_at'], name='noticeboard_created_95978d_idx')],
            },
        ),
    ]
