# Generated by Django 4.2.27 on 2026-02-23 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('performance', 'Performance')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('department_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['report_type'], name='reports_rep_report__08e150_idx'), models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_42264d_idx')],
            },
        ),
    ]
