# Generated by Django 4.2.27 on 2026-02-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Start date for the reporting week')),
                ('week_end', models.DateField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('next_week_plan', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', '-submitted_at'],
                'indexes': [models.Index(fields=['week_start'], name='reports_wee_week_st_0ef4bf_idx'), models.Index(fields=['employee', 'week_start'], name='reports_wee_employe_b7104f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('employee', 'week_start'), name='unique_weekly_report_per_employee_week'),
        ),
    ]
