# Generated by Django 4.2.27 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_weeklyreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='submission_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RemoveConstraint(
            model_name='weeklyreport',
            name='unique_weekly_report_per_employee_week',
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(
                fields=('employee', 'week_start', 'submission_number'),
                name='unique_weekly_report_per_employee_week_submission',
            ),
        ),
    ]
