# Generated by Django 4.2.27 on 2026-02-24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_weeklyreport_submission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='request_all_employees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='requested_employees',
            field=models.ManyToManyField(blank=True, related_name='report_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
