# Generated by GitHub Copilot on 2026-02-24

from django.db import migrations, models


def backfill_task_positions(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    statuses = ['TODO', 'IN_PROGRESS', 'DONE', 'REDO']
    for status in statuses:
        tasks = list(
            Task.objects.filter(status=status)
            .order_by('deadline', '-created_at', 'id')
            .only('id', 'position')
        )
        for idx, task in enumerate(tasks, start=1):
            task.position = idx
        if tasks:
            Task.objects.bulk_update(tasks, ['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_task_positions, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'position'], name='tasks_task_status_pos_idx'),
        ),
    ]
