# Generated by Django 4.2.27 on 2026-02-24 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'position', 'deadline', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status_88f9b1_idx',
            old_name='tasks_task_status_pos_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('USER', 'One person')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='visible_to',
            field=models.ForeignKey(blank=True, help_text='If set to "One person", only that user (and admins) can see this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['visibility'], name='tasks_task_visibil_82dbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['visibility', 'visible_to'], name='tasks_task_visibil_898bda_idx'),
        ),
    ]
