# Generated by Django 4.2.27 on 2026-02-23 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_employeedepartmentrole_employeedocument_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction')], max_length=20)),
                ('taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(default=django.utils.timezone.localdate)),
                ('applies_to_month', models.DateField(help_text='Use first day of month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Clearance'), ('CLEARED', 'Cleared (Deduct)'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('clearance_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('ON_HOLD', 'On Hold (Penalty Clearance)'), ('CLEARED', 'Cleared')], default='ON_HOLD', max_length=20)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('clearance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='locked',
            field=models.BooleanField(default=False, help_text='When locked, this payroll run should not be recalculated.'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='allowance_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='deduction_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='is_held',
            field=models.BooleanField(default=False, help_text='Held until penalty clearance is completed.'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='penalty_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('month',), name='unique_payroll_run_month'),
        ),
        migrations.AddField(
            model_name='salaryvoucher',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_salary_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryvoucher',
            name='payslip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_voucher', to='payroll.payslip'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='employees.department'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payitemtype',
            index=models.Index(fields=['kind'], name='payroll_pay_kind_c2394d_idx'),
        ),
        migrations.AddIndex(
            model_name='payitemtype',
            index=models.Index(fields=['is_active'], name='payroll_pay_is_acti_1b8249_idx'),
        ),
        migrations.AddField(
            model_name='employeepayitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pay_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayitem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_items', to='payroll.payitemtype'),
        ),
        migrations.AddIndex(
            model_name='salaryvoucher',
            index=models.Index(fields=['status'], name='payroll_sal_status_8b15f8_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['status'], name='payroll_pen_status_1f9bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['employee', 'applies_to_month'], name='payroll_pen_employe_2681f7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayitem',
            index=models.Index(fields=['employee', 'is_active'], name='payroll_emp_employe_06e4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayitem',
            index=models.Index(fields=['item_type', 'is_active'], name='payroll_emp_item_ty_ed11eb_idx'),
        ),
    ]
