# Generated by Django 4.2.27 on 2026-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='code',
            field=models.SlugField(blank=True, help_text='Short unique code, e.g. annual, sick, maternity', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['is_active'], name='leave_mgmt__is_acti_40fd43_idx'),
        ),
    ]
